### ISSUE TITLE
Does not work with Neo4j Desktop 5.18.1

### ISSUE THREAD

**Issue by kuczera** [THM-Graphs/neo4j-atag#9]
Part of the error message:

`2024-05-06 08:12:57.275+0000 ERROR [o.n.g.f.DatabaseManagementServiceFactory] Error starting Neo4j database server at /Users/kuczera/Library/Application Support/Neo4j Desktop/Application/relate-data/dbmss/dbms-49c29766-e365-4a32-840e-2eb38272c790/data/databases
org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.neo4j.causalclustering.discovery.parallel.LifeElement@31e84f10' was successfully initialized, but failed to start. Please see the attached cause exception "Invalid signature file digest for Manifest main attributes".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:364) ~[neo4j-common-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:91) ~[neo4j-common-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.parallel.DistributingTopologyService.start(DistributingTopologyService.java:109) ~[neo4j-discovery-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.parallel.ParallelTopologyService.start(ParallelTopologyService.java:86) ~[neo4j-discovery-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:347) ~[neo4j-common-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:91) ~[neo4j-common-5.18.1.jar:5.18.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:267) [neo4j-5.18.1.jar:5.18.1]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:211) [neo4j-5.18.1.jar:5.18.1]
	at com.neo4j.server.enterprise.EnterpriseDBMSProvider.createManagementService(EnterpriseDBMSProvider.java:39) [neo4j-enterprise-5.18.1.jar:5.18.1]
	at com.neo4j.server.enterprise.EnterpriseDBMSProvider.<init>(EnterpriseDBMSProvider.java:29) [neo4j-enterprise-5.18.1.jar:5.18.1]
	at com.neo4j.server.enterprise.EnterpriseDBMSFactory.createManagementService(EnterpriseDBMSFactory.java:19) [neo4j-enterprise-5.18.1.jar:5.18.1]
	at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:25) [neo4j-enterprise-5.18.1.jar:5.18.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.18.1.jar:5.18.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.18.1.jar:5.18.1]
	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:19) [neo4j-enterprise-5.18.1.jar:5.18.1]
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:347) ~[?:?]
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:289) ~[?:?]
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:327) ~[?:?]
	at java.util.jar.JarVerifier.update(JarVerifier.java:239) ~[?:?]
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:761) ~[?:?]
	at java.util.jar.JarFile.getInputStream(JarFile.java:847) ~[?:?]
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:187) ~[?:?]
	at java.net.URL.openStream(URL.java:1161) ~[?:?]
	at akka.util.ManifestInfo.liftedTree1$1(ManifestInfo.scala:119) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.util.ManifestInfo.<init>(ManifestInfo.scala:116) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.util.ManifestInfo$.createExtension(ManifestInfo.scala:49) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.util.ManifestInfo$.createExtension(ManifestInfo.scala:27) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1165) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ExtensionId.apply(Extension.scala:78) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ExtensionId.apply$(Extension.scala:77) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.util.ManifestInfo$.apply(ManifestInfo.scala:27) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1040) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1029) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1029) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1052) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:272) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystem$.create(ActorSystem.scala:196) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at akka.actor.ActorSystem.create(ActorSystem.scala) ~[akka-actor_2.13-2.6.19.jar:2.6.19]
	at com.neo4j.causalclustering.discovery.akka.system.ActorSystemFactory.createActorSystem(ActorSystemFactory.java:55) ~[neo4j-discovery-akka-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.akka.system.ActorSystemComponents.<init>(ActorSystemComponents.java:25) ~[neo4j-discovery-akka-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.akka.system.ActorSystemLifecycle.createClusterActorSystem(ActorSystemLifecycle.java:79) ~[neo4j-discovery-akka-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.akka.AkkaTopologyService.start0(AkkaTopologyService.java:146) ~[neo4j-discovery-akka-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:116) ~[neo4j-common-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.SafeLifecycle.start(SafeLifecycle.java:128) ~[neo4j-common-5.18.1.jar:5.18.1]
	at com.neo4j.causalclustering.discovery.parallel.LifeElement.start(LifeElement.java:55) ~[neo4j-discovery-5.18.1.jar:5.18.1]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:347) ~[neo4j-common-5.18.1.jar:5.18.1]
	... 14 more
`

**Comment by sarmbruster** [comment]
a fix will be included in next release
